CONFIG_LOG_OUTPUT=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
# USART3 is taken by the lighthouse deck at 230400 baud; use CRTP radio console
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_I2C_LOG_LEVEL_WRN=y
CONFIG_UART_LOG_LEVEL_WRN=y
