"""
test_choreo_sim.py — the replay/simulation harness (sdk/tools/choreo_sim.py).

Two modes with very different jobs:

  --simulate  is the sub-second feedback loop for someone editing a
              .choreo.toml.  If it wedges, mis-counts ticks, or reports a
              script as complete when it is not, the authoring surface
              lies to its author.

  --replay    re-drives the Python engine with inputs recorded from a real
              run and diffs the result.  Its value is entirely in catching
              divergences, so the tests here inject them deliberately: a
              harness that reports OK on a mutated recording is worthless.

The replay fixture in data/ is generated by helpers.py, not captured from
Webots — see record_reference_run() for what that does and does not prove.
"""

import csv
import subprocess
import sys
from pathlib import Path

import pytest
from helpers import (DATA_DIR, REPO_ROOT, SCRIPT_TOML, record_reference_run,
                     write_telemetry)

import choreo_sim
from tapestry.bse import BSEDirectiveType

SIM = REPO_ROOT / "sdk/tools/choreo_sim.py"
FIXTURE = DATA_DIR / "replay_change_partners_0.csv"


def run_cli(*args):
    return subprocess.run([sys.executable, str(SIM), *map(str, args)],
                          capture_output=True, text=True, cwd=REPO_ROOT)


def rows_of(path: Path):
    with open(path, newline="") as f:
        return list(csv.reader(f))


# ── --simulate ───────────────────────────────────────────────────────────────

@pytest.mark.parametrize("n", [1, 2, 4, 7])
def test_simulate_runs_the_shipped_script_to_completion(n):
    rc, records = choreo_sim.simulate(SCRIPT_TOML, n, speed_mps=2.0,
                                      verbose=False)
    assert rc == 0
    assert set(records) == set(range(n))
    assert all(len(r) > 0 for r in records.values())


def test_simulate_terminates_within_the_scripts_total_time_bound():
    """choreoc guarantees every step a hard bound, so the tick loop needs
    no separate safety cap — that guarantee is what is being checked."""
    from tapestry.script_toml import parse_file
    script = parse_file(SCRIPT_TOML)
    max_ticks = -(-script.total_timeout_ms // choreo_sim.WM_CYCLE_MS)
    _, records = choreo_sim.simulate(SCRIPT_TOML, 2, 2.0, False)
    assert len(records[0]) <= max_ticks


def test_simulate_gives_every_element_the_same_world_each_tick():
    """The snapshot is taken before any element ticks, so dict iteration
    order cannot change the outcome — a swap must look identical from
    both sides."""
    _, a = choreo_sim.simulate(SCRIPT_TOML, 2, 2.0, False)
    _, b = choreo_sim.simulate(SCRIPT_TOML, 2, 2.0, False)
    assert [(r.x, r.y, r.script_step) for r in a[0]] == \
           [(r.x, r.y, r.script_step) for r in b[0]]


def test_simulate_actually_swaps_the_two_stations():
    """change-partners is a swap; if the harness reported completion
    without the elements exchanging positions it would be useless."""
    _, records = choreo_sim.simulate(SCRIPT_TOML, 2, 2.0, False)
    start0 = (records[0][0].x, records[0][0].y)
    start1 = (records[1][0].x, records[1][0].y)
    end0 = (records[0][-1].x, records[0][-1].y)
    assert end0 == pytest.approx(start1, abs=0.3)
    assert end0 != pytest.approx(start0, abs=0.3)


def test_simulate_rejects_a_zero_element_run():
    rc, records = choreo_sim.simulate(SCRIPT_TOML, 0, 2.0, False)
    assert rc == 1 and records == {}


def test_simulate_reports_a_script_error_instead_of_raising(tmp_path):
    bad = tmp_path / "bad.choreo.toml"
    bad.write_text('choreo = "bad"\n[[steps]]\nhold = { }\n')
    assert choreo_sim.simulate(bad, 2, 2.0, False) == (1, {})


def test_simulate_reports_a_missing_script_instead_of_raising(tmp_path):
    assert choreo_sim.simulate(tmp_path / "absent.toml", 2, 2.0, False) \
        == (1, {})


def test_a_slower_platform_still_completes_the_script():
    """The step bounds, not the integrator, decide when a step ends."""
    rc, records = choreo_sim.simulate(SCRIPT_TOML, 2, speed_mps=0.2,
                                      verbose=False)
    assert rc == 0
    assert records[0][-1].script_step in (-1, 2)


def test_a_hold_directive_leaves_the_element_where_it_is():
    """HOLD / MAINTAIN_SPRING / IDLE carry no single-point target this toy
    integrator can move toward — physics is Webots' job."""
    _, records = choreo_sim.simulate(SCRIPT_TOML, 2, 2.0, False)
    hold_ticks = [r for r in records[0][:5]
                  if r.directive_type != BSEDirectiveType.MOVE_TO_POINT]
    for r in hold_ticks:
        assert (r.x, r.y) == (records[0][0].x, records[0][0].y)


def test_simulate_cli_exits_zero_and_summarises():
    r = run_cli("--simulate", "--script", SCRIPT_TOML, "--elements", 3)
    assert r.returncode == 0, r.stderr
    assert "change-partners" in r.stdout
    assert "3/3 element(s) completed" in r.stdout


# ── --replay ─────────────────────────────────────────────────────────────────

def test_the_committed_recording_replays_without_divergence():
    """The regression bar: the current engine must reproduce, tick for
    tick, the outputs recorded alongside these inputs."""
    rc, records = choreo_sim.replay(SCRIPT_TOML, FIXTURE, 1e-3, 5, False)
    assert rc == 0
    assert len(records) == len(rows_of(FIXTURE)) - 1


def test_the_recording_exercises_all_three_steps():
    """A fixture that never leaves step 0 would pass vacuously."""
    with open(FIXTURE, newline="") as f:
        steps = {int(row["script_step"]) for row in csv.DictReader(f)}
    assert {0, 1, 2}.issubset(steps)


def test_the_recording_carries_the_gossiped_achievement_bit():
    """A scope="all" step advances on peers' achieved bits; a recording
    without them replays on its timeout instead and reports a divergence
    that is the recorder's fault, not the engine's."""
    with open(FIXTURE, newline="") as f:
        first = next(csv.DictReader(f))
    assert '"achieved"' in first["wm_json"]


def test_replay_warns_when_the_recording_predates_the_achieved_bit(tmp_path,
                                                                   capsys):
    stripped = tmp_path / "old.csv"
    rows = rows_of(FIXTURE)
    wm_col = rows[0].index("wm_json")
    import json
    for row in rows[1:]:
        entries = json.loads(row[wm_col])
        for e in entries:
            e.pop("achieved", None)
        row[wm_col] = json.dumps(entries, separators=(",", ":"))
    with open(stripped, "w", newline="") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)

    choreo_sim.replay(SCRIPT_TOML, stripped, 1e-3, 0, False)
    assert "records no per-peer 'achieved' bit" in capsys.readouterr().err


@pytest.mark.parametrize("column,mutate", [
    ("script_step",     lambda v: "9"),
    ("goal_achieved",   lambda v: "0" if v == "1" else "1"),
    ("directive_type",  lambda v: "0" if v != "0" else "2"),
    ("script_complete", lambda v: "0" if v == "1" else "1"),
])
def test_replay_catches_a_mutated_output_column(column, mutate, tmp_path):
    """The harness only earns its keep if it fails on a real difference."""
    rows = rows_of(FIXTURE)
    col = rows[0].index(column)
    rows[40][col] = mutate(rows[40][col])
    mutated = tmp_path / "mutated.csv"
    with open(mutated, "w", newline="") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)
    rc, _ = choreo_sim.replay(SCRIPT_TOML, mutated, 1e-3, 5, False)
    assert rc == 1


def test_replay_catches_a_target_that_drifts_past_the_tolerance(tmp_path):
    rows = rows_of(FIXTURE)
    col = rows[0].index("directive_target_x")
    rows[40][col] = f"{float(rows[40][col]) + 0.5:.4f}"
    mutated = tmp_path / "mutated.csv"
    with open(mutated, "w", newline="") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)
    assert choreo_sim.replay(SCRIPT_TOML, mutated, 1e-3, 5, False)[0] == 1


def test_replay_tolerates_float32_rounding_within_eps_tol(tmp_path):
    """C float32 vs Python float64 and a "%.4f" CSV round-trip mean exact
    equality is the wrong bar — but only just below the tolerance."""
    rows = rows_of(FIXTURE)
    col = rows[0].index("directive_target_x")
    for row in rows[1:]:
        row[col] = f"{float(row[col]) + 5e-4:.6f}"
    nudged = tmp_path / "nudged.csv"
    with open(nudged, "w", newline="") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)
    assert choreo_sim.replay(SCRIPT_TOML, nudged, 1e-3, 5, False)[0] == 0


def test_replay_rejects_an_empty_recording(tmp_path):
    empty = write_telemetry(tmp_path / "empty.csv", [])
    assert choreo_sim.replay(SCRIPT_TOML, empty, 1e-3, 5, False) == (1, [])


def test_replay_rejects_a_file_mixing_two_elements(tmp_path):
    """choreo_telemetry.c writes one file per element; a merged file would
    silently interleave two state machines."""
    rows = rows_of(FIXTURE)
    col = rows[0].index("element_id")
    rows[30][col] = "1"
    mixed = tmp_path / "mixed.csv"
    with open(mixed, "w", newline="") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)
    rc, records = choreo_sim.replay(SCRIPT_TOML, mixed, 1e-3, 5, False)
    assert rc == 1
    assert len(records) == 29


def test_a_truncated_final_row_stops_the_replay_without_crashing(tmp_path):
    """A capture killed rather than closed leaves a partial line — a
    recording artifact, not a divergence."""
    text = FIXTURE.read_text().rstrip("\n").rsplit("\n", 1)[0]
    truncated = tmp_path / "truncated.csv"
    truncated.write_text(text + "\n999,99.9,0,1.0,1.0,2,2,0,5,2,0,1,2,1.0,1.0,"
                                '"[{""id"":0,""x"":1.0\n')
    rc, records = choreo_sim.replay(SCRIPT_TOML, truncated, 1e-3, 5, False)
    assert rc == 0
    assert len(records) == len(rows_of(FIXTURE)) - 2


def test_replay_rejects_a_script_the_recording_cannot_have_run(tmp_path):
    unadvanceable = tmp_path / "stall.choreo.toml"
    unadvanceable.write_text('choreo = "stall"\n[[steps]]\n'
                             'hold = { duration = "0.05s" }\n')
    # A script whose steps are all valid still submits; the mismatch shows
    # up as divergence, not rejection.  Rejection is for a script the SDK
    # itself refuses.
    rc, _ = choreo_sim.replay(unadvanceable, FIXTURE, 1e-3, 1, False)
    assert rc == 1


def test_replay_reports_a_script_error_instead_of_raising(tmp_path):
    bad = tmp_path / "bad.choreo.toml"
    bad.write_text('choreo = "bad"\n[[steps]]\nhold = { }\n')
    assert choreo_sim.replay(bad, FIXTURE, 1e-3, 5, False) == (1, [])


def test_max_report_caps_the_detail_printed_not_the_verdict(tmp_path, capsys):
    rows = rows_of(FIXTURE)
    col = rows[0].index("script_step")
    for row in rows[1:]:
        row[col] = "9"
    mutated = tmp_path / "all-wrong.csv"
    with open(mutated, "w", newline="") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)
    rc, _ = choreo_sim.replay(SCRIPT_TOML, mutated, 1e-3, 2, False)
    err = capsys.readouterr().err
    assert rc == 1
    assert err.count("divergence at tick") == 2
    assert "FAIL" in err


def test_replay_cli_exits_zero_on_the_committed_fixture():
    r = run_cli("--replay", "--script", SCRIPT_TOML, "--telemetry", FIXTURE)
    assert r.returncode == 0, r.stderr
    assert "0 divergences" in r.stdout


# ── Recording format ─────────────────────────────────────────────────────────

def test_wm_entry_flags_are_coerced_to_real_booleans():
    entries = choreo_sim.parse_wm_entries(
        '[{"id":0,"x":1.0,"y":2.0,"is_active":true,"is_stale":false,'
        '"is_self":true,"achieved":true}]')
    e = entries[0]
    assert (e["is_active"], e["is_stale"], e["is_self"], e["achieved"]) \
        == (True, False, True, True)


def test_an_absent_achieved_key_defaults_to_not_achieved():
    entries = choreo_sim.parse_wm_entries(
        '[{"id":0,"x":0,"y":0,"is_active":true,"is_stale":false,'
        '"is_self":true}]')
    assert entries[0]["achieved"] is False


def test_the_committed_fixture_is_reproducible():
    """helpers.py regenerates data/ — if this fails the fixture and the
    generator have parted ways, and the replay test above is checking a
    recording nothing produces any more."""
    assert rows_of(FIXTURE)[1:] == [
        [str(f) for f in row] for row in record_reference_run(SCRIPT_TOML)]


# ── CLI argument handling ────────────────────────────────────────────────────

@pytest.mark.parametrize("args,message", [
    (["--replay", "--script", "S"], "--replay requires --telemetry"),
    (["--simulate", "--script", "S"], "--simulate requires --elements"),
    (["--simulate", "--script", "S", "--elements", "2", "--out", "x.png"],
     "--out has no effect without --plot"),
    (["--script", "S"], "one of the arguments"),
])
def test_incoherent_argument_combinations_are_refused(args, message):
    r = run_cli(*[a if a != "S" else str(SCRIPT_TOML) for a in args])
    assert r.returncode != 0
    assert message in r.stderr


def test_the_two_modes_are_mutually_exclusive():
    r = run_cli("--replay", "--simulate", "--script", SCRIPT_TOML)
    assert r.returncode != 0
    assert "not allowed with" in r.stderr


def test_plotting_stays_a_lazy_import():
    """Compiling or replaying a script must stay dependency-free (see
    choreoc.py: "standard library only... nothing to install"), so
    matplotlib may only be imported inside plot_records()."""
    import ast
    tree = ast.parse((REPO_ROOT / "sdk/tools/choreo_sim.py").read_text())
    module_level = [n for n in tree.body if isinstance(n, (ast.Import,
                                                          ast.ImportFrom))]
    names = {a.name.split(".")[0] for n in module_level
             if isinstance(n, ast.Import) for a in n.names}
    names |= {(n.module or "").split(".")[0] for n in module_level
              if isinstance(n, ast.ImportFrom)}
    assert "matplotlib" not in names
